// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyvronvnxeuieuiwwhmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dnJvbnZueGV1aWV1aXd3aG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzQ3ODEsImV4cCI6MjA2ODkxMDc4MX0.BnOfe3YMYvTKFpgjqaDsGUz95EbKNJZRCpuIn3bPlXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});